version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    environment:
      ghAccessToken: '1eae45af888ed99d311d4ef9928bf9be9417cb16'

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn bootstrap
      - run: yarn test
