service: crowdpay

package:
  # individually: true   # comment out during developemnt
  exclude:
    - ./**

plugins:
  - serverless-webpack
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - IssueTable
          - Arn

functions:
  github-issue:
    handler: lib/github-issue.handler
    package:
      include:
        - lib/github-issue.js
    environment:
      ghAccessToken: ${file(.env.json):ghAccessToken}
    events:
     - http:
         path: github-issue
         method: any
         cors: true
resources:
  Resources:
    # DyanmoDB
    IssueTable: ${file(configs/dynamodb.yml):IssueTable}
